### ISSUE TITLE
Question about using (or not using) a command prefix

### ISSUE THREAD

**Issue by MostHated** [Necroforger/dgrouter#5]
Hey there,  
 This seems great. I am excited to make use of it. I had a question though. How might you go about allowing the bot to pick up certain things by text alone without the need for the command prefix? Example being, I would certainly want some commands to be prefixed, but say, someone was just writing a normal chat message and they are not aware of any actual commands or prefixes but they say something that I would like to recognize and act upon, how would I go about specifying which matcher needs a prefix and which would not?

Thanks,
-MH

**Comment by Necroforger** [comment]
Prefixes are handled by the [FindAndExecute](https://github.com/Necroforger/dgrouter/blob/master/exrouter/router_wrapper.go#L81) helper function. If you want all routes to not require a prefix you could try using `""` as the prefix parameter and using [Regex Matchers](https://github.com/Necroforger/dgrouter/blob/master/examples/pingpong/pingpong.go#L39) on your routes to specify more accurately what text you're trying to match. The OnMatch function accepts a `func (string) bool` so you can implement whatever logic you need for the route to activate.

Then you could require other routes to have prefices like this.
```go
r := exrouter.New()
on := func(s string, handler func(exrouter.Context)) {
    r.On("!" + s, handler)
}
on("prefixroute", route)
on("another_prefix_route", route)
r.On("no_prefix", route)
```

If you want to do a complicated type of matching or argument parsing you may have to rewrite the FindAndExecute function.

It may also be helpful to add a `Prefix` field to the Route struct itself and implement a custom matcher based on the [NameMatcher](https://github.com/Necroforger/dgrouter/blob/master/matchers.go#L14) to check if the text begins with route prefix and contains the route name afterwards.

This would require that you fork the repository.

**Comment by MostHated** [comment]
I definitely appreciate the reply. There is really only 1 thing currently that I would want to watch for using Regex. I had written a [bot in Python ](https://github.com/instance-id/verifier) that lets people enter their invoice numbers into a PM with the bot which then verifies their purchase and takes action from there. Unfortunately though, a lot of people don't seem to understand the concept of a private message and just willy-nilly post their invoice numbers into public chat. So the idea was to watch for a specific character length of numbers, or if it began with INV, then delete it from chat asap so someone else who didn't actually have one didn't take it and act like it's theirs.

I have been meaning to learn Go, so I figured that trying to convert my bot over from Python to Go might be a good learning experience since I already know what it is supposed to do, it lets me focus on figuring out the translation in the language instead of focusing on how I wanted the bot to function overall. 

That being said, unfortunately,I am quite new to Go. While I definitely like the idea of being able to contribute and make modifications such as adding a custom matcher, realistically, it might take a bit of time until I am familiar enough with the language to be able to do that. Perhaps as I work my way through converting each feature over I will gain enough knowledge and confidence to try and attempt that.

I certainly do appreciate the information, and I will definitely keep it in mind as I progress.
Thanks,
-MH

**Comment by Necroforger** [comment]
You could also parse the messages in the message handler. That would be the simplest way.
https://github.com/Necroforger/dgrouter/blob/master/examples/pingpong/pingpong.go#L52

Above router.FindAndExecute, enter your logic for checking for invoice numbers outside of PMs.
