### ISSUE TITLE
How to receive messages?

### ISSUE THREAD

**Issue by MostHated** [Necroforger/dgrouter#8]
Hey again,
    I have everything working great now and am moving right along, but I can't quite figure out how to receive messages?

Here is how I would go about it in Python with the bot framework I was using:

```python
async def wp_email_check(self, ctx):
    def check(m):
        return m.author == ctx.message.author
    await ctx.send(text.email_capture_during_verification())  # -- This would send the text out "Please enter your email address"
    email = await self.bot.wait_for('message', check=check)   # -- Then this would start an async method which would listen for input 
```

What is the proper way to go about getting input with this system?
Thanks,
-MH

**Comment by MostHated** [comment]
Unless there is something built in that I am missing, I came across this, and I think it might work out ok from the little bit of testing I have tried.  https://github.com/tehstone/GoKyogre/blob/d36d833de2249590d86b4279d4ab4f2091625104/src/util/waitutils.go

**Comment by Necroforger** [comment]
Did you figure this out? you should be using the handler function you register with `session.AddHandler()`

**Comment by MostHated** [comment]
Yeah, I sure did. I came across that link I posted a little bit after I made this. I took that and adapted it a bit and so far it is working great.

**Comment by Necroforger** [comment]
Handlers return a function that will unregister themselves when called. I would suggest adding a new handler from within the handler and repeatedly read messages until you receive one from the original sender.

I use this method in another library and repeatedly call it until I get a message I'm looking for. Because it's a channel you can use it with `select` to implement timeouts. 
https://github.com/Necroforger/dgwidgets/blob/master/util.go#L8

**Comment by Necroforger** [comment]
And here is how I use these functions
https://github.com/Necroforger/dgwidgets/blob/master/widget.go#L104

**Comment by MostHated** [comment]
That was one thing I was worried about. From the looks of it, it seemed like it would just take whatever next, so what you mentioned is definitely a good idea. My testing so far has been simple, not even more than one message at a time, so I had not ran into that yet, but I am quite sure it will show it's head as soon as I get deeper into testing.

**Comment by MostHated** [comment]
Is the issue still present when are dealing with DM Channels? From what I gather it seems like it generates a channel id on opening a DM session? I have not actually compared ID's that I can remember. Can it not use that to retain a message "session" and perhaps have a handler be aware of what message channel to listen on in place of repeatedly checking messages?

**Comment by Necroforger** [comment]
I haven't tried it in DM channels but I assume it would work.

**Comment by MostHated** [comment]
The main reason I wonder is my bot is mostly for utility for the channel owner, I don't plan on having many general public functions. I am eager to test it all out though. I still definitely want to follow your advice, at the same time, I think I might first test it a bunch as is, so that when strange things do occur, I can see them first hand, see what and how they mess up so I can try to learn from it.
