### ISSUE TITLE
Are there routers like this for non-discord, non-web application?

### ISSUE THREAD

**Issue by MostHated** [Necroforger/dgrouter#9]
Heya,  
    I really like this router. I was wondering if you happen to know if any exist that might be similar but are for internal use within an application so that if you want to add a new "feature" or "action" to your application, you can just use the template and add a new cmd file, code it up to do what you need and add it to the list of routes like you would with this? I was not sure how to word it when searching. I tried "language:go router NOT http NOT web" but it didn't really come back with what I was hoping. Pretty much just DG router minus integration with Discord, lol.

Thanks,
-MH

**Comment by MostHated** [comment]
I was able to do something of a workaround by using the following:

```go

Commands: []*cli.Command{
			{
				Name: func() string {
					result := fmt.Sprintf((*cmd.DbSetup).GetCommand(cmd.NewDbSetup(appData)))
					return result
				}(),
				Aliases: []string{"ds"},
				Usage: func() string {
					result := fmt.Sprintf((*cmd.DbSetup).GetDescription(cmd.NewDbSetup(appData)))
					return result
				}(),
				Action: func(c *cli.Context) error {
					(*cmd.DbSetup).Handle(cmd.NewDbSetup(appData))
					log.Infof("DB Setup Complete")
					return nil
				},
			}

```

It at least lets me use the template pretty well, so that's ok I suppose for now. 👍

**Comment by Necroforger** [comment]
A command line argument parser might be what you're looking for.
Something like [kingping](https://github.com/alecthomas/kingpin) or [kong](https://github.com/alecthomas/kong).
You could also use the [flag](https://golang.org/pkg/flag/) package from the standard library.

kong allows you to register commands using struct definitions/tags similar to how you demonstrated above.
```go
var CLI struct {
  Rm struct {
    Force     bool `help:"Force removal."`
    Recursive bool `help:"Recursively remove files."`

    Paths []string `arg name:"path" help:"Paths to remove." type:"path"`
  } `cmd help:"Remove files."`

  Ls struct {
    Paths []string `arg optional name:"path" help:"Paths to list." type:"path"`
  } `cmd help:"List paths."`
}
```

If you want to use dgrouter for something non-discord related, you could modify the [exrouter](https://github.com/Necroforger/dgrouter/tree/master/exrouter) example to use your own `Context` type.

The types you need to change are as follows.
____________________
- This function initializes your context, finds a command, parses arguments, then executes the corresponding handler. 
https://github.com/Necroforger/dgrouter/blob/040421b5a83e7914e9cacbd56ad573f685f2f65b/exrouter/router_wrapper.go#L81

- Change what information the `Context` stores, maybe include a pointer to your application state
https://github.com/Necroforger/dgrouter/blob/040421b5a83e7914e9cacbd56ad573f685f2f65b/exrouter/context.go#L13


- change the way `Context` is initialized
https://github.com/Necroforger/dgrouter/blob/040421b5a83e7914e9cacbd56ad573f685f2f65b/exrouter/context.go#L82

_________

You could also use the dgrouter package directly, but it wouldn't be type safe as the context type and middleware functions operate on `interface{}`
